import { jsPDF } from 'jspdf';
import { projectState } from '$state/project.svelte.js';
import { solverState } from '$state/solver.svelte.js';
import { getBuildingCoverage, floorCoverage } from '$state/optimizer.svelte.js';
import { floorState, switchFloor } from '$state/floor-state.svelte.js';
import type { CanvasEngine } from '$canvas/engine.js';

/** Wait for Svelte effects + async decodes to settle after a floor switch. */
function waitForRender(): Promise<void> {
	return new Promise((resolve) => {
		// Two rAFs to flush Svelte effects, then a timeout for async image/mask decode
		requestAnimationFrame(() => requestAnimationFrame(() => setTimeout(resolve, 200)));
	});
}

const BRAND_COLOR: [number, number, number] = [0, 200, 200];
const GRAY: [number, number, number] = [100, 100, 110];
const DARK: [number, number, number] = [30, 30, 40];
const LIGHT_BG: [number, number, number] = [245, 246, 250];
const TABLE_HEADER_BG: [number, number, number] = [35, 40, 55];
const TABLE_ALT_BG: [number, number, number] = [248, 249, 252];

const bandLabels: Record<string, string> = {
	'2.4ghz': '2.4 GHz',
	'5ghz': '5 GHz',
	'6ghz': '6 GHz'
};

function drawHeader(doc: jsPDF, pageWidth: number, margin: number) {
	// Brand bar
	doc.setFillColor(...BRAND_COLOR);
	doc.rect(0, 0, pageWidth, 3, 'F');

	// Logo text
	doc.setFontSize(11);
	doc.setFont('helvetica', 'bold');
	doc.setTextColor(...BRAND_COLOR);
	doc.text('Deconflict', margin, 12);

	// Tagline
	doc.setFontSize(7);
	doc.setFont('helvetica', 'normal');
	doc.setTextColor(...GRAY);
	doc.text('WiFi Channel Planner', margin + 28, 12);

	// Divider
	doc.setDrawColor(220, 220, 230);
	doc.setLineWidth(0.3);
	doc.line(margin, 16, pageWidth - margin, 16);

	doc.setTextColor(...DARK);
}

function drawFooter(doc: jsPDF, pageWidth: number, pageHeight: number, margin: number) {
	const y = pageHeight - 8;
	doc.setFontSize(6.5);
	doc.setFont('helvetica', 'normal');
	doc.setTextColor(...GRAY);
	doc.text('Generated by Deconflict — deconflict.pages.dev', margin, y);
	doc.text(`Page ${(doc as any).getCurrentPageInfo().pageNumber}`, pageWidth - margin, y, {
		align: 'right'
	});
	doc.setTextColor(...DARK);
}

export async function exportPdf(engine: CanvasEngine): Promise<void> {
	const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
	const pageWidth = doc.internal.pageSize.getWidth();
	const pageHeight = doc.internal.pageSize.getHeight();
	const margin = 18;
	const contentWidth = pageWidth - margin * 2;

	const dateStr = new Date().toLocaleDateString('en-US', {
		year: 'numeric',
		month: 'long',
		day: 'numeric'
	});
	const apCount = projectState.aps.length;
	const floorCount = floorState.floors.length;
	const sortedFloors = [...floorState.floors].sort((a, b) => a.level - b.level);

	// ─── PAGE 1: Cover + Layout ──────────────────────────────────────

	drawHeader(doc, pageWidth, margin);

	// Layout pages — one per floor
	const originalFloorId = floorState.currentFloorId;
	let isFirstLayout = true;
	let y = 0;

	for (const floor of sortedFloors) {
		// Switch to this floor and wait for rendering to settle
		if (floor.id !== floorState.currentFloorId) {
			switchFloor(floor.id);
			engine.markDirty();
			await waitForRender();
		}

		if (!isFirstLayout) {
			doc.addPage();
		}
		drawHeader(doc, pageWidth, margin);

		if (isFirstLayout) {
			// Title block on first page only
			y = 26;
			doc.setFontSize(20);
			doc.setFont('helvetica', 'bold');
			doc.setTextColor(...DARK);
			doc.text(projectState.name, margin, y);

			y += 8;
			doc.setFontSize(9);
			doc.setFont('helvetica', 'normal');
			doc.setTextColor(...GRAY);
			doc.text(
				`${dateStr}  •  ${apCount} access point${apCount !== 1 ? 's' : ''}  •  ${floorCount} floor${floorCount !== 1 ? 's' : ''}`,
				margin,
				y
			);
			doc.setTextColor(...DARK);
			y += 10;
		} else {
			y = 24;
		}

		// Floor label
		doc.setFontSize(11);
		doc.setFont('helvetica', 'bold');
		doc.setTextColor(...DARK);
		doc.text(floor.name, margin, y);

		const fc = floorCoverage.get(floor.id);
		if (fc) {
			doc.setFontSize(8);
			doc.setFont('helvetica', 'normal');
			doc.setTextColor(...GRAY);
			doc.text(`Coverage: ${fc.coverage}%`, pageWidth - margin, y, { align: 'right' });
		}
		doc.setTextColor(...DARK);
		y += 6;

		const canvasImg = captureCanvas(engine);
		const imgY = y;
		const maxImgHeight = pageHeight - imgY - margin - 5;
		const aspectRatio = canvasImg.width / canvasImg.height;
		let imgWidth = contentWidth;
		let imgHeight = imgWidth / aspectRatio;
		if (imgHeight > maxImgHeight) {
			imgHeight = maxImgHeight;
			imgWidth = imgHeight * aspectRatio;
		}
		const imgX = margin + (contentWidth - imgWidth) / 2;
		doc.addImage(canvasImg.data, 'JPEG', imgX, imgY, imgWidth, imgHeight);

		drawFooter(doc, pageWidth, pageHeight, margin);
		isFirstLayout = false;
	}

	// Restore original floor
	if (floorState.currentFloorId !== originalFloorId) {
		switchFloor(originalFloorId);
		engine.markDirty();
		await waitForRender();
	}

	// ─── PAGE 2+: AP Schedule ────────────────────────────────────────

	doc.addPage();
	drawHeader(doc, pageWidth, margin);

	y = 24;
	doc.setFontSize(14);
	doc.setFont('helvetica', 'bold');
	doc.text('Access Point Schedule', margin, y);

	y += 10;

	// Build column definitions
	const hasModel = projectState.aps.some((ap) => ap.modelLabel);

	type Col = {
		header: string;
		width: number;
		getValue: (ap: (typeof projectState.aps)[0]) => string;
	};
	const cols: Col[] = [
		{ header: 'NAME', width: 35, getValue: (ap) => ap.name },
		{ header: 'MODEL', width: hasModel ? 50 : 35, getValue: (ap) => ap.modelLabel ?? 'Custom' },
		{ header: 'BAND', width: 22, getValue: (ap) => bandLabels[ap.band] ?? ap.band },
		{ header: 'WIDTH', width: 22, getValue: (ap) => `${ap.channelWidth} MHz` },
		{
			header: 'CHANNEL',
			width: 22,
			getValue: (ap) => (ap.assignedChannel !== null ? String(ap.assignedChannel) : '—')
		},
		{ header: 'POWER', width: 22, getValue: (ap) => `${ap.power} dBm` }
	];

	for (const floor of sortedFloors) {
		const floorAps = projectState.aps.filter((ap) => ap.floorId === floor.id);
		if (floorAps.length === 0 && floorCount > 1) continue;
		const apsToShow = floorCount === 1 ? projectState.aps : floorAps;

		// Floor section header
		if (floorCount > 1) {
			if (y > pageHeight - 30) {
				doc.addPage();
				drawHeader(doc, pageWidth, margin);
				y = 24;
			}
			doc.setFillColor(...LIGHT_BG);
			doc.roundedRect(margin, y - 4, contentWidth, 8, 1, 1, 'F');
			doc.setFontSize(9);
			doc.setFont('helvetica', 'bold');
			doc.setTextColor(...DARK);
			doc.text(floor.name, margin + 3, y + 1);

			// Floor coverage if available
			const fc = floorCoverage.get(floor.id);
			if (fc) {
				doc.setFont('helvetica', 'normal');
				doc.setTextColor(...GRAY);
				doc.text(`Coverage: ${fc.coverage}%`, margin + contentWidth - 3, y + 1, {
					align: 'right'
				});
			}
			doc.setTextColor(...DARK);
			y += 10;
		}

		// Table header
		doc.setFillColor(...TABLE_HEADER_BG);
		doc.rect(margin, y - 4, contentWidth, 7, 'F');
		doc.setFontSize(6.5);
		doc.setFont('helvetica', 'bold');
		doc.setTextColor(255, 255, 255);

		let x = margin + 2;
		for (const col of cols) {
			doc.text(col.header, x, y);
			x += col.width;
		}
		doc.setTextColor(...DARK);
		y += 8;

		// Table rows
		doc.setFontSize(8);
		doc.setFont('helvetica', 'normal');

		for (let idx = 0; idx < apsToShow.length; idx++) {
			if (y > pageHeight - 15) {
				drawFooter(doc, pageWidth, pageHeight, margin);
				doc.addPage();
				drawHeader(doc, pageWidth, margin);
				y = 24;
			}

			const ap = apsToShow[idx]!;
			if (idx % 2 === 0) {
				doc.setFillColor(...TABLE_ALT_BG);
				doc.rect(margin, y - 4, contentWidth, 7, 'F');
			}

			x = margin + 2;
			for (const col of cols) {
				doc.text(col.getValue(ap), x, y);
				x += col.width;
			}
			y += 7;
		}

		y += 4;
	}

	// ─── Summary ─────────────────────────────────────────────────────

	if (y > pageHeight - 35) {
		drawFooter(doc, pageWidth, pageHeight, margin);
		doc.addPage();
		drawHeader(doc, pageWidth, margin);
		y = 24;
	}

	y += 4;
	doc.setDrawColor(220, 220, 230);
	doc.line(margin, y, margin + contentWidth, y);
	y += 8;

	doc.setFontSize(10);
	doc.setFont('helvetica', 'bold');
	doc.text('Summary', margin, y);
	y += 7;

	doc.setFontSize(8.5);
	doc.setFont('helvetica', 'normal');

	const summaryItems: string[] = [];
	summaryItems.push(
		`${apCount} access point${apCount !== 1 ? 's' : ''} across ${floorCount} floor${floorCount !== 1 ? 's' : ''}`
	);

	if (solverState.lastResult) {
		summaryItems.push(
			`${solverState.lastResult.colorCount} channel${solverState.lastResult.colorCount !== 1 ? 's' : ''} used, ${solverState.lastResult.conflicts.length} conflict${solverState.lastResult.conflicts.length !== 1 ? 's' : ''}`
		);
	}

	if (floorCoverage.size > 0) {
		for (const floor of sortedFloors) {
			const fc = floorCoverage.get(floor.id);
			if (fc) {
				summaryItems.push(`${floor.name} coverage: ${fc.coverage}%`);
			}
		}
		if (floorCount > 1 && floorCoverage.size > 1) {
			summaryItems.push(`Building average coverage: ${getBuildingCoverage()}%`);
		}
	}

	for (const item of summaryItems) {
		doc.text(`•  ${item}`, margin + 2, y);
		y += 5;
	}

	drawFooter(doc, pageWidth, pageHeight, margin);

	// Save
	const filename = projectState.name.replace(/[^a-zA-Z0-9-_]/g, '_');
	doc.save(`${filename}-report.pdf`);
}

/** Capture the current canvas view as a JPEG data URL. */
function captureCanvas(engine: CanvasEngine): { data: string; width: number; height: number } {
	const canvasEl = engine.canvas;
	const scale = 2;
	const srcWidth = canvasEl.width / (window.devicePixelRatio || 1);
	const srcHeight = canvasEl.height / (window.devicePixelRatio || 1);
	const tempCanvas = document.createElement('canvas');
	tempCanvas.width = srcWidth * scale;
	tempCanvas.height = srcHeight * scale;
	const ctx = tempCanvas.getContext('2d')!;
	ctx.scale(scale, scale);

	ctx.fillStyle = '#0a0c12';
	ctx.fillRect(0, 0, srcWidth, srcHeight);

	const dpr = scale;
	const rc = {
		ctx,
		camera: engine.camera,
		width: srcWidth,
		height: srcHeight,
		dpr,
		compositeOffscreen: (offscreen: HTMLCanvasElement, alpha = 1) => {
			ctx.resetTransform();
			ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
			if (alpha < 1) ctx.globalAlpha = alpha;
			ctx.drawImage(offscreen, 0, 0);
			if (alpha < 1) ctx.globalAlpha = 1;
		}
	};

	for (const layer of engine.layers) {
		if (!layer.visible) continue;
		if (layer.id === 'grid' || layer.id === 'selection-rect') continue;
		ctx.save();
		layer.render(rc);
		ctx.restore();
	}

	return {
		data: tempCanvas.toDataURL('image/jpeg', 0.9),
		width: srcWidth,
		height: srcHeight
	};
}
